# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dmas/robot_dreams/robot-dreams-code-fpga/task10-microblaze/task10-microblaze.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_3/design_1_lmb_bram_3.xci
# IP: The module: 'design_1_lmb_bram_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dmas/robot_dreams/robot-dreams-code-fpga/task10-microblaze/task10-microblaze.gen/sources_1/bd/design_1/ip/design_1_lmb_bram_3/design_1_lmb_bram_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_lmb_bram_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/dmas/robot_dreams/robot-dreams-code-fpga/task10-microblaze/task10-microblaze.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_3/design_1_lmb_bram_3.xci
# IP: The module: 'design_1_lmb_bram_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dmas/robot_dreams/robot-dreams-code-fpga/task10-microblaze/task10-microblaze.gen/sources_1/bd/design_1/ip/design_1_lmb_bram_3/design_1_lmb_bram_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_lmb_bram_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
